### PR TITLE
Use Bioc actions, change to devel

### PR DESCRIPTION
**Pull request by csoneson**

### CODE REVIEW

**Comment by machlabd** [comment]
thanks for updating this! I haven't yet nuked my laptop and set up access to my GitHub repos again. Would you mind also adding the missing information on citing monaLisa? Like issue and page numbers, I left the fields in the citation file, just empty.

**Comment by csoneson** [comment]
Oh, right, good point - done. I bumped the version so that it can propagate also on Bioc

**Comment by machlabd** [comment]
Thank you! The `textVersion` also needs updating, let me see how it is with the other packages.

**Comment by csoneson** [comment]
Oops, sorry - went too fast

**Comment by machlabd** [comment]
So it would become: "Machlab D, Burger L, Soneson C, Rijli FM, Schübeler D, Stadler MB. monaLisa: an R/Bioconductor package for identifying regulatory motifs. Bioinformatics 38(9):2624-2625 (2022)."

**Comment by machlabd** [comment]
aha you were faster! Thanks again :)

**Review by mbstadler — APPROVED** [review]

**Pull request merged**
